name: Publish Package to npmjs
on:
  push:
    branches:
      - main

jobs:
  build-and-publish-plugins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          token: ${{ secrets.PAT_SERVICE_ACCOUNT }}

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - run: npm publish --access public
        if: github.event_name == 'push' && github.event.pull_request.head.repo.full_name != github.repository
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: .

      - name: "Commit new version to main and create tag"
        if: github.event_name == 'push' && github.event.pull_request.head.repo.full_name != github.repository
        run: |
          version=$(jq -r '.version' src/package.json)
          git config --global user.email "service@jan.ai"
          git config --global user.name "Service Account"
          git add src/package.json
          git commit -m "${GITHUB_REPOSITORY}: Update tag build $version"
          git -c http.extraheader="AUTHORIZATION: bearer ${{ secrets.PAT_SERVICE_ACCOUNT }}" push origin HEAD:main
          git tag -a $version -m "${GITHUB_REPOSITORY}: Update tag build $version"
          git -c http.extraheader="AUTHORIZATION: bearer ${{ secrets.PAT_SERVICE_ACCOUNT }}" push origin $version
